# action.yml
name: "Merge API"
description: "Merge an AppSync API into an AppSync Merged API"
inputs:
  results:
    required: true
    type: string
  region:
    required: false
    type: string
    default: "us-east-1"
  decrypt:
    required: false
    type: boolean
    default: true
  access_key_id:
    required: false
    type: string
  secret_access_key:
    required: false
    type: string
  session_token:
    required: false
    type: string
    default: ""
  profile:
    required: false
    type: string
    default: ""
  resolve_values:
    required: false
    type: boolean
    default: false
outputs:
  association_ids:
    description: "The ids of the AppSync API associations"

runs:
  using: "node20"
  main: "dist/index.js"
