# action.yml
name: "Merge API"
description: "Merge an AppSync API into an AppSync Merged API"
inputs:
  source:
    required: true
    type: string
  target:
    required: true
    type: string
  region:
    required: false
    type: string
    default: "us-east-1"
  decrypt:
    required: false
    type: boolean
    default: true
  access_key_id:
    required: false
    type: string
  secret_access_key:
    required: false
    type: string
  session_token:
    required: false
    type: string
    default: ""
  profile:
    required: false
    type: string
    default: ""
  resolve_values:
    required: false
    type: boolean
    default: false
outputs:
  association_id:
    description: "The id of the AppSync API association"

runs:
  using: "node20"
  main: "dist/index.js"
