name: "Setup Java"
description: "Setup Java for a Maven project"
inputs:
  username:
    required: true
    type: string
    default: github
  password:
    required: true
    type: string
  organization:
    required: true
    type: string
  version:
    required: false
    type: string
    default: 17
  ref:
    required: false
    type: string
    default: ""
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.version }}
    - uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - shell: bash
      run: |
        cp ${{ github.action_path }}/settings.xml ~/.m2/settings.xml
        sed -i 's/\${ORGANIZATION}/${{ inputs.organization }}/g' ~/.m2/settings.xml
        sed -i 's/\${MAVEN_USERNAME}/${{ inputs.username }}/g' ~/.m2/settings.xml
        sed -i 's/\${MAVEN_PASSWORD}/${{ inputs.password }}/g' ~/.m2/settings.xml
