name: "Setup Terragrunt"
description: "Setup Terragrunt for a project"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - shell: bash
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        echo "$HOME/.tfenv/bin" >> $GITHUB_PATH
        git clone --depth=1 https://github.com/tgenv/tgenv.git ~/.tgenv
        echo "$HOME/.tgenv/bin" >> $GITHUB_PATH
    - shell: bash
      run: |
        tfenv install
        tfenv use
        tgenv install
        tgenv use
        terraform -version
        terragrunt -version
