name: "terragrunt-build-deploy"
on:
  workflow_call:
    inputs:                           ## inputs if "required" MUST be in caller workflow
      TF_VAR_stage:                   ## dev, stg, or prd
        required: true
        type: string
      JIRA_ENV_TYPE:                  ## development, staging, or production
        required: true
        type: string
      TF_VAR_az_region:
        required: true
        type: string
      TF_VAR_image_version:
        required: false
        type: string
      TERRAGRUNT_PARALLELISM:
        required: false
        type: number
      TF_VERSION:
        required: true
        type: string
      TG_VERSION:
        required: true
        type: string
      TF_WORKING_DIR:
        required: true
        type: string
      TERRAFORM_PRE_APPLY_SUBFOLDERS:
        required: true
        type: string
      TERRAGRUNT_LOG_LEVEL:
        required: true
        type: string
      NODE_VERSION:
        required: true
        type: string
      RUNNER_TYPE:
        required: true
        type: string        
    secrets:
      TF_VAR_subscription_id:
        required: false
      SECRET_ACCESS_KEY:
        required: false
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
      JIRA_CLIENT_ID:
        required: true
      JIRA_CLIENT_SECRET:
        required: true
      TF_VAR_prd_subscription_id:
        required: false
      TF_VAR_dev_subscription_id:
        required: false
env:
  TF_VAR_stage: ${{ inputs.TF_VAR_stage }}
  TF_VAR_image_version: ${{ inputs.TF_VAR_image_version }}
  TF_VAR_az_region: ${{ inputs.TF_VAR_az_region }}
  JIRA_ENV_TYPE: ${{ inputs.JIRA_ENV_TYPE }}
  TF_VERSION: ${{ inputs.TF_VERSION }}
  TG_VERSION: ${{ inputs.TG_VERSION }}
  TF_WORKING_DIR: ${{ inputs.TF_WORKING_DIR }}
  TERRAFORM_PRE_APPLY_SUBFOLDERS: ${{ inputs.TERRAFORM_PRE_APPLY_SUBFOLDERS }}
  TERRAGRUNT_LOG_LEVEL: ${{ inputs.TERRAGRUNT_LOG_LEVEL }}
  TERRAGRUNT_PARALLELISM: ${{ inputs.TERRAGRUNT_PARALLELISM }}
  NODE_VERSION: ${{ inputs.NODE_VERSION }}
  TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_prd_subscription_id: ${{ secrets.TF_VAR_prd_subscription_id }}
  TF_VAR_dev_subscription_id: ${{ secrets.TF_VAR_dev_subscription_id }}

permissions: read-all

jobs:
  terragrunt-pre-apply:
    name: "Terragrunt Pre Apply"
    runs-on: ${{ inputs.RUNNER_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo version
        run: |
          echo "${{ env.TF_VAR_image_version }}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - name: Lint Terraform
        run: terraform fmt -recursive -check
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Lint Terragrunt
        run: terragrunt hclfmt --terragrunt-check
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SECRET_ACCESS_KEY }}
      - name: Pre-validate Apply Steps
        env:
          FILES: ${{env.TERRAFORM_PRE_APPLY_SUBFOLDERS}}
        run: for f in $FILES; do terragrunt apply -auto-approve --terragrunt-working-dir $f --terragrunt-non-interactive --terragrunt-log-level ${{ env.TERRAGRUNT_LOG_LEVEL }}; done
  terragrunt-plan:
    # START CONFIGURATION
    name: "Terragrunt Plan"
    needs: terragrunt-pre-apply
    runs-on: ${{ inputs.RUNNER_TYPE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SECRET_ACCESS_KEY }}
      - name: Verify Node.js installation
        run: node -v
      - name: Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          parse-all-commits: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format Jira Keys
        run: |
          JIRA_KEYS="${{ steps.jira_keys.outputs.jira-keys }}"
          echo "${JIRA_KEYS}" >> .tmp_jira_keys
          echo "JIRA_KEYS=$(grep -o '[A-Z]\+-[0-9]\+' .tmp_jira_keys | tr '\n' ',' | sed 's/,*$//')" >> $GITHUB_ENV
      - name: Echo Jira Keys
        run: |
          echo "Jira Keys: ${{env.JIRA_KEYS}}"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - name: Validate Terraform
        run: terragrunt validate
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Plan Terraform
        if: ${{ ( inputs.TERRAGRUNT_PARALLELISM == '0') }}
        run: terragrunt run-all plan --terragrunt-non-interactive --terragrunt-log-level ${{ env.TERRAGRUNT_LOG_LEVEL }}
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Plan Terraform Parallel
        if: ${{ ( inputs.TERRAGRUNT_PARALLELISM != '0') }}
        run: terragrunt run-all plan --terragrunt-non-interactive --terragrunt-parallelism ${{ inputs.TERRAGRUNT_PARALLELISM }} --terragrunt-log-level ${{ env.TERRAGRUNT_LOG_LEVEL }}
        working-directory: ${{ env.TF_WORKING_DIR }} 
      - name: Confirm Build
        run: |
          echo "Planning ${{ inputs.TF_VAR_stage }}..."
          echo "github.event_name: ${{github.event_name}}"
          echo "github.ref: ${{github.ref}}"
          echo "BUILD_STATE=successful"  >> $GITHUB_ENV
      - name: Confirm Build State and Jira Key Values
        if: always()
        run: |
          echo "BUILD_STATE: ${{env.BUILD_STATE}}"
          echo "Jira Keys: ${{env.JIRA_KEYS}}"
      - name: Failed Deployment
        if: failure()
        run: echo "BUILD_STATE=failed" >> $GITHUB_ENV
      - name: Push Build Info to Jira
        if: "${{ env.JIRA_KEYS != '' }}"
        id: push_build_info_to_jira
        uses: HighwayThree/jira-upload-build-info@master
        with:
          pipeline-id: '${{ github.repository }} ${{ github.workflow }} ${{ inputs.TF_VAR_stage }}'
          client-id: '${{ secrets.JIRA_CLIENT_ID }}'
          client-secret: '${{ secrets.JIRA_CLIENT_SECRET }}'
          cloud-instance-base-url: 'https://gravicore.atlassian.net/'
          issue-keys: "${{ env.JIRA_KEYS }}"
          build-state: "${{ env.BUILD_STATE }}"
          build-display-name: '${{ github.workflow }}: ${{ inputs.TF_VAR_stage }}'
          build-url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
          build-ref-url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
  terragrunt-apply:
    # START CONFIGURATION
    name: "Terragrunt Apply"
    needs: terragrunt-plan
    # END CONFIGURATION
    runs-on: ${{ inputs.RUNNER_TYPE }}
    environment:
      name: ${{ inputs.TF_VAR_stage }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SECRET_ACCESS_KEY }}          
      - name: Verify Node.js installation
        run: node -v     
      - name: Parse Jira Keys from Commit
        id: jira_keys
        if: always()
        uses: HighwayThree/jira-extract-issue-keys@master
        with:
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          parse-all-commits: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Format Jira Keys
        run: |
          JIRA_KEYS="${{ steps.jira_keys.outputs.jira-keys }}"
          echo "${JIRA_KEYS}" >> .tmp_jira_keys
          echo "JIRA_KEYS=$(grep -o '[A-Z]\+-[0-9]\+' .tmp_jira_keys | tr '\n' ',' | sed 's/,*$//')" >> $GITHUB_ENV
      - name: Setup Terraform          
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.2.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}
      - name: Apply Terraform
        if: ${{ ( inputs.TERRAGRUNT_PARALLELISM != '') }}
        run: terragrunt run-all apply --terragrunt-non-interactive --terragrunt-parallelism ${{ inputs.TERRAGRUNT_PARALLELISM }} --terragrunt-log-level ${{ env.TERRAGRUNT_LOG_LEVEL }}
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Apply Terraform
        if: ${{ ( inputs.TERRAGRUNT_PARALLELISM == '') }}
        run: terragrunt run-all apply --terragrunt-non-interactive --terragrunt-log-level ${{ env.TERRAGRUNT_LOG_LEVEL }}
        working-directory: ${{ env.TF_WORKING_DIR }}
      - name: Confirm Deploy
        run: |
          echo "Deploying to ${{ inputs.TF_VAR_stage }}..."
          echo "github.event_name: ${{github.event_name}}"
          echo "github.ref: ${{github.ref}}"
          echo "DEPLOY_STATE=successful"  >> $GITHUB_ENV
      - name: Confirm Deploy State and Jira Key Values
        if: always()
        run: |
          echo "DEPLOY_STATE: ${{env.DEPLOY_STATE}}"
          echo "Jira Keys: ${{env.JIRA_KEYS}}"
      - name: Failed Deployment
        if: failure()
        run: echo "DEPLOY_STATE=failed" >> $GITHUB_ENV
      - name: Push Deployment Info to Jira
        if: "${{ env.JIRA_KEYS != '' }}"
        id: push_deployment_info_to_jira
        uses: HighwayThree/jira-upload-deployment-info@master
        with:
          client-id: "${{ secrets.JIRA_CLIENT_ID }}"
          client-secret: "${{ secrets.JIRA_CLIENT_SECRET }}"
          cloud-instance-base-url: "https://gravicore.atlassian.net/"
          deployment-sequence-number: "${{ github.run_id }}"
          update-sequence-number: "${{ github.run_id }}"
          issue-keys: "${{ env.JIRA_KEYS }}"
          display-name: "${{ inputs.TF_VAR_stage }} Run ID #${{github.run_id}}"
          url: "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          description: "${{ inputs.TF_VAR_stage }} Deployment"
          last-updated: "${{github.event.head_commit.timestamp}}"
          label: "${{ inputs.TF_VAR_stage }} Deployment Label"
          state: "${{env.DEPLOY_STATE}}"
          pipeline-id: "${{ github.repository }} ${{ github.workflow }}"
          pipeline-display-name: "${{ github.workflow }} (#${{ github.run_number }})"
          pipeline-url: "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
          environment-id: "${{ inputs.TF_VAR_stage }}"
          environment-display-name: "${{ inputs.TF_VAR_stage }}"
          environment-type: "${{ env.JIRA_ENV_TYPE }}"