name: Sonar Scan
on:
  workflow_call:
    inputs:
      REPOSITORY_NAME:        
        required: true
        type: string
      SONAR_HOST_URL:        
        required: true
        type: string
      SONAR_TOKEN:        
        required: true
        type: string

env:
  REPOSITORY_NAME: ${{ inputs.REPOSITORY_NAME }}

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Bash Command - Find Repo Name
        run: |
          echo "This is a bash command"
          pwd
          echo "REPO_NAME=${{ inputs.REPOSITORY_NAME }}" >> $GITHUB_ENV
          echo "$REPO_NAME"

      - name: Run Bash Command - Create project in SonarQube
        run: |
          echo "$REPO_NAME"
          PROJECT_KEY=$REPO_NAME
          PROJECT_NAME=$REPO_NAME
                    
          RESPONSE=$(curl -s -X POST "${{ inputs.SONAR_HOST_URL }}/api/projects/create" \
              -u "${{ inputs.SONAR_TOKEN }}:" \
              -d "project=${PROJECT_KEY}" \
              -d "name=${PROJECT_NAME}")

          if echo "$RESPONSE" | grep -q "A similar key already exists:"; then
              echo "Project '${PROJECT_KEY}' already exists."
          elif echo "$RESPONSE" | grep -q "\"project\":{\"key\":\"${PROJECT_KEY}\""; then
              echo "Project created successfully."
          else
              echo "Failed to create the project. Response: $RESPONSE"
          fi

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.1.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=$REPO_NAME
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.java
