name: "terragrunt-build-deploy"
on:
  workflow_call:
    inputs:
      TF_VAR_stage:
        required: true
        type: string
      JIRA_ENV_TYPE:
        required: true
        type: string
      TERRAGRUNT_PARALLELISM:
        required: false
        type: number
      TF_VERSION:
        required: true
        type: string
      TG_VERSION:
        required: true
        type: string
      TF_WORKING_DIR:
        required: true
        type: string
      TERRAFORM_PRE_APPLY_SUBFOLDERS:
        required: true
        type: string
      TERRAGRUNT_LOG_LEVEL:
        required: true
        type: string
      ARTIFACTS_INCLUDE:
        required: false
        type: boolean
      LAMBDA_MOVE_ARTIFACT_SCRIPT:
        required: false
        type: string
      RUNNER:
        required: true
        type: string
      UPLOAD_ARTIFACT_NAME:
        required: false
        type: string
      ATLASSIAN_URL:
        required: true
        type: string
      APPSYNC_MERGE:
        required: true
        type: string
    secrets:
      DEV_AWS_ACCESS_KEY_ID:
        required: false
      DEV_AWS_ACCESS_KEY_SECRET:
        required: false
      STG_AWS_ACCESS_KEY_ID:
        required: false
      STG_AWS_ACCESS_KEY_SECRET:
        required: false
      PRD_AWS_ACCESS_KEY_ID:
        required: false
      PRD_AWS_ACCESS_KEY_SECRET:
        required: false
      JIRA_CLIENT_ID:
        required: true
      JIRA_CLIENT_SECRET:
        required: true
jobs:
  terragrunt:
    uses: gravicore/github-actions/.github/workflows/terragrunt-build-deploy.yml@main
    with:
      TF_VAR_stage: ${{ inputs.TF_VAR_stage }}
      JIRA_ENV_TYPE: ${{ inputs.JIRA_ENV_TYPE }}
      TERRAGRUNT_PARALLELISM: ${{ inputs.TERRAGRUNT_PARALLELISM }}
      TF_VERSION: ${{ inputs.TF_VERSION }}
      TG_VERSION: ${{ inputs.TG_VERSION }}
      TF_WORKING_DIR: ${{ inputs.TF_WORKING_DIR }}
      TERRAFORM_PRE_APPLY_SUBFOLDERS: ${{ inputs.TERRAFORM_PRE_APPLY_SUBFOLDERS }}
      TERRAGRUNT_LOG_LEVEL: ${{ inputs.TERRAGRUNT_LOG_LEVEL }}
      ARTIFACTS_INCLUDE: ${{ inputs.ARTIFACTS_INCLUDE }}
      LAMBDA_MOVE_ARTIFACT_SCRIPT: ${{ inputs.LAMBDA_MOVE_ARTIFACT_SCRIPT }}
      RUNNER: ${{ inputs.RUNNER }}
      UPLOAD_ARTIFACT_NAME: ${{ inputs.UPLOAD_ARTIFACT_NAME }}
      ATLASSIAN_URL: ${{ inputs.ATLASSIAN_URL }}
      APPSYNC_MERGE: ${{ inputs.APPSYNC_MERGE }}
    secrets: inherit

  appsync:
    runs-on: ${{ inputs.RUNNER }}
    name: "AppSync Merge"
    needs: terragrunt
    environment:
      name: ${{ inputs.TF_VAR_stage }}
    steps:
      - uses: gravicore/github-actions/.github/actions/merge-api@main
        with:
          results: ${{ needs.terragrunt.outputs.results }}
          access_key_id: ${{ (secrets.DEV_AWS_ACCESS_KEY_ID || secrets.STG_AWS_ACCESS_KEY_ID || secrets.PRD_AWS_ACCESS_KEY_ID) }}
          secret_access_key: ${{ (secrets.DEV_AWS_ACCESS_KEY_SECRET || secrets.STG_AWS_ACCESS_KEY_SECRET || secrets.PRD_AWS_ACCESS_KEY_SECRET) }}
